### ISSUE TITLE
Handling bounces and spam compliant from Streams

### ISSUE THREAD

**Issue by gustavo-2830** [spatie/laravel-mailcoach-postmark-feedback#7]
Hello, I was wondering if the package is going to be able to work with Streams' webhook to handle bounces and spam compliant. The webhook for Streams includes both events as a "SubscriptionChange" record type.

Here is an example webhook from their website:
![image](https://user-images.githubusercontent.com/38366461/93129881-b5e2e400-f69f-11ea-9ae3-0eb125854fd7.png)

Right now the package works perfectly but only with Postmark's transactional emails.

**Comment by freekmurze** [comment]
Currently we don't support streams. If this is something that is easy to implement, we'd accept a PR with tests that adds this to the package.
